//
// CommentRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CommentRequestDTO: Codable {

    public var commentText: String?
    public var user: String?

    public init(commentText: String?, user: String?) {
        self.commentText = commentText
        self.user = user
    }


}

