//
// CommentResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CommentResponseDTO: Codable {

    public var commentDate: String?
    public var commentId: Int?
    public var commentText: String?
    public var postId: Int?
    public var user: UserResponseDTO?

    public init(commentDate: String?, commentId: Int?, commentText: String?, postId: Int?, user: UserResponseDTO?) {
        self.commentDate = commentDate
        self.commentId = commentId
        self.commentText = commentText
        self.postId = postId
        self.user = user
    }


}

