//
// Experience.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Experience: Codable {

    public var companyId: String?
    public var companyName: String?
    public var department: String?
    public var experienceId: Int?
    public var stillWork: Bool?
    public var workerId: String?

    public init(companyId: String?, companyName: String?, department: String?, experienceId: Int?, stillWork: Bool?, workerId: String?) {
        self.companyId = companyId
        self.companyName = companyName
        self.department = department
        self.experienceId = experienceId
        self.stillWork = stillWork
        self.workerId = workerId
    }


}

