//
// IDCommentRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IDCommentRequestDTO: Codable {

    public var commentId: String?

    public init(commentId: String?) {
        self.commentId = commentId
    }


}

