//
// LikeResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LikeResponseDTO: Codable {

    public var likeId: Int?
    public var post: PostResponseDTO?
    public var userId: String?

    public init(likeId: Int?, post: PostResponseDTO?, userId: String?) {
        self.likeId = likeId
        self.post = post
        self.userId = userId
    }


}

