//
// LikeRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LikeRequestDTO: Codable {

    public var user: String?

    public init(user: String?) {
        self.user = user
    }


}

