//
// Message.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Message: Codable {

    public var messageDate: String?
    public var messageId: Int?
    public var messageReceiverUserId: String?
    public var messageSenderUserId: String?
    public var messageText: String?

    public init(messageDate: String?, messageId: Int?, messageReceiverUserId: String?, messageSenderUserId: String?, messageText: String?) {
        self.messageDate = messageDate
        self.messageId = messageId
        self.messageReceiverUserId = messageReceiverUserId
        self.messageSenderUserId = messageSenderUserId
        self.messageText = messageText
    }


}

