//
// PostRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostRequestDTO: Codable {

    public var createdDateTime: String?
    public var department: String?
    public var mediaUrl: String?
    public var postDescription: String?
    public var postType: Int?
    public var tags: [String]?
    public var userId: String?

    public init(createdDateTime: String?, department: String?, mediaUrl: String?, postDescription: String?, postType: Int?, tags: [String]?, userId: String?) {
        self.createdDateTime = createdDateTime
        self.department = department
        self.mediaUrl = mediaUrl
        self.postDescription = postDescription
        self.postType = postType
        self.tags = tags
        self.userId = userId
    }


}

