//
// PostResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PostResponseDTO: Codable {

    public var commentCount: Int?
    public var commentList: [Comment]?
    public var createdDateTime: String?
    public var department: String?
    public var isLiked: Bool?
    public var isWatched: Bool?
    public var likeCount: Int?
    public var likeList: [UserResponseDTO]?
    public var mediaUrl: String?
    public var postDescription: String?
    public var postId: Int?
    public var postType: Int?
    public var tags: [String]?
    public var user: UserResponseDTO?

    public init(commentCount: Int?, commentList: [Comment]?, createdDateTime: String?, department: String?, isLiked: Bool?, isWatched: Bool?, likeCount: Int?, likeList: [UserResponseDTO]?, mediaUrl: String?, postDescription: String?, postId: Int?, postType: Int?, tags: [String]?, user: UserResponseDTO?) {
        self.commentCount = commentCount
        self.commentList = commentList
        self.createdDateTime = createdDateTime
        self.department = department
        self.isLiked = isLiked
        self.isWatched = isWatched
        self.likeCount = likeCount
        self.likeList = likeList
        self.mediaUrl = mediaUrl
        self.postDescription = postDescription
        self.postId = postId
        self.postType = postType
        self.tags = tags
        self.user = user
    }


}

