//
// SearchRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchRequest: Codable {

    public enum UserTypes: String, Codable { 
        case investor = "INVESTOR"
        case startup = "STARTUP"
        case developer = "DEVELOPER"
        case normalUser = "NORMAL_USER"
    }
    public var fullName: String?
    public var userTypes: [UserTypes]?

    public init(fullName: String?, userTypes: [UserTypes]?) {
        self.fullName = fullName
        self.userTypes = userTypes
    }


}

