//
// Sort.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Sort: Codable {

    public var empty: Bool?
    public var sorted: Bool?
    public var unsorted: Bool?

    public init(empty: Bool?, sorted: Bool?, unsorted: Bool?) {
        self.empty = empty
        self.sorted = sorted
        self.unsorted = unsorted
    }


}

