//
// StartUpsDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StartUpsDto: Codable {

    public var companyId: String?
    public var companyName: String?

    public init(companyId: String?, companyName: String?) {
        self.companyId = companyId
        self.companyName = companyName
    }


}

