//
// Timestamp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Timestamp: Codable {

    public var date: Int?
    public var day: Int?
    public var hours: Int?
    public var minutes: Int?
    public var month: Int?
    public var nanos: Int?
    public var seconds: Int?
    public var time: Int64?
    public var timezoneOffset: Int?
    public var year: Int?

    public init(date: Int?, day: Int?, hours: Int?, minutes: Int?, month: Int?, nanos: Int?, seconds: Int?, time: Int64?, timezoneOffset: Int?, year: Int?) {
        self.date = date
        self.day = day
        self.hours = hours
        self.minutes = minutes
        self.month = month
        self.nanos = nanos
        self.seconds = seconds
        self.time = time
        self.timezoneOffset = timezoneOffset
        self.year = year
    }


}

