//
// UserMessageDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserMessageDTO: Codable {

    public var firstName: String?
    public var lastMessage: String?
    public var lastName: String?
    public var profileImgUrl: String?
    public var userId: String?

    public init(firstName: String?, lastMessage: String?, lastName: String?, profileImgUrl: String?, userId: String?) {
        self.firstName = firstName
        self.lastMessage = lastMessage
        self.lastName = lastName
        self.profileImgUrl = profileImgUrl
        self.userId = userId
    }


}

