//
// View.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct View: Codable {

    public var contentType: String?

    public init(contentType: String?) {
        self.contentType = contentType
    }


}

