//
// WatchPost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WatchPost: Codable {

    public var post: Int?
    public var user: User?
    public var watchedPostId: Int?

    public init(post: Int?, user: User?, watchedPostId: Int?) {
        self.post = post
        self.user = user
        self.watchedPostId = watchedPostId
    }


}

