//
// Watcher.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Watcher: Codable {

    public var beingWatch: Bool?
    public var _id: Int?
    public var user: User?
    public var watchMapId: UUID?
    public var watchingUser: String?

    public init(beingWatch: Bool?, _id: Int?, user: User?, watchMapId: UUID?, watchingUser: String?) {
        self.beingWatch = beingWatch
        self._id = _id
        self.user = user
        self.watchMapId = watchMapId
        self.watchingUser = watchingUser
    }

    public enum CodingKeys: String, CodingKey { 
        case beingWatch
        case _id = "id"
        case user
        case watchMapId
        case watchingUser
    }


}

