//
// Watch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Watch: Codable {

    public var watcherId: String?
    public var watchingId: String?

    public init(watcherId: String?, watchingId: String?) {
        self.watcherId = watcherId
        self.watchingId = watchingId
    }


}

