//
// DiscoverControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DiscoverControllerAPI {
    /**
     popüler postları görüntüler
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func discoverPostsUsingGET(completion: @escaping ((_ data: [PostResponseDTO]?,_ error: Error?) -> Void)) {
        discoverPostsUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     popüler postları görüntüler
     - GET /api/v1/discover/post
     - examples: [{output=none}]

     - returns: RequestBuilder<[PostResponseDTO]> 
     */
    open class func discoverPostsUsingGETWithRequestBuilder() -> RequestBuilder<[PostResponseDTO]> {
        let path = "/api/v1/discover/post"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[PostResponseDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     popüler kullanıcıları görüntüler
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func discoverUserUsingGET(completion: @escaping ((_ data: [UserResponseDTO]?,_ error: Error?) -> Void)) {
        discoverUserUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     popüler kullanıcıları görüntüler
     - GET /api/v1/discover/suggested
     - examples: [{output=none}]

     - returns: RequestBuilder<[UserResponseDTO]> 
     */
    open class func discoverUserUsingGETWithRequestBuilder() -> RequestBuilder<[UserResponseDTO]> {
        let path = "/api/v1/discover/suggested"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[UserResponseDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
