//
// ErrorControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ErrorControllerAPI {
    /**
     invalidToken
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func invalidTokenUsingGET(completion: @escaping ((_ data: [String:String]?,_ error: Error?) -> Void)) {
        invalidTokenUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     invalidToken
     - GET /error/invalid_auth
     - examples: [{output=none}]

     - returns: RequestBuilder<[String:String]> 
     */
    open class func invalidTokenUsingGETWithRequestBuilder() -> RequestBuilder<[String:String]> {
        let path = "/error/invalid_auth"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[String:String]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
