//
// SearchControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SearchControllerAPI {
    /**
     kullanıcı aramak için kullanılır
     
     - parameter searchRequest: (body) searchRequest 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchUserUsingGET(searchRequest: SearchRequest, completion: @escaping ((_ data: [UserResponseDTO]?,_ error: Error?) -> Void)) {
        searchUserUsingGETWithRequestBuilder(searchRequest: searchRequest).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     kullanıcı aramak için kullanılır
     - GET /api/v1/search
     - examples: [{output=none}]
     
     - parameter searchRequest: (body) searchRequest 

     - returns: RequestBuilder<[UserResponseDTO]> 
     */
    open class func searchUserUsingGETWithRequestBuilder(searchRequest: SearchRequest) -> RequestBuilder<[UserResponseDTO]> {
        let path = "/api/v1/search"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: searchRequest)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[UserResponseDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
