//
// UserAuthControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class UserAuthControllerAPI {
    /**
     kayıt
     
     - parameter userRequestDTO: (body) userRequestDTO 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addNewUserUsingPOST(userRequestDTO: UserRequestDTO, completion: @escaping ((_ data: UserResponseDTO?,_ error: Error?) -> Void)) {
        addNewUserUsingPOSTWithRequestBuilder(userRequestDTO: userRequestDTO).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     kayıt
     - POST /auth/signUp
     - examples: [{output=none}]
     
     - parameter userRequestDTO: (body) userRequestDTO 

     - returns: RequestBuilder<UserResponseDTO> 
     */
    open class func addNewUserUsingPOSTWithRequestBuilder(userRequestDTO: UserRequestDTO) -> RequestBuilder<UserResponseDTO> {
        let path = "/auth/signUp"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userRequestDTO)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<UserResponseDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Giriş
     
     - parameter userAuthRequestDto: (body) userAuthRequestDto 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func loginUsingPOST(userAuthRequestDto: UserAuthRequestDto, completion: @escaping ((_ data: JSONValue?,_ error: Error?) -> Void)) {
        loginUsingPOSTWithRequestBuilder(userAuthRequestDto: userAuthRequestDto).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Giriş
     - POST /auth/login
     - examples: [{output=none}]
     
     - parameter userAuthRequestDto: (body) userAuthRequestDto 

     - returns: RequestBuilder<JSONValue> 
     */
    open class func loginUsingPOSTWithRequestBuilder(userAuthRequestDto: UserAuthRequestDto) -> RequestBuilder<JSONValue> {
        let path = "/auth/login"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userAuthRequestDto)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<JSONValue>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    
    
    open class func loginUserSelf(mail: String, password: String, completion: @escaping  ((_ data: DataResponse<Any>)->())) {
        
        let h: HTTPHeaders = ["Content-Type": "application/json",
        "Accept": "application/json"]
        Alamofire.request(URL(string: "http://ec2-18-156-84-119.eu-central-1.compute.amazonaws.com/auth/login")!, method: .post, parameters: ["email": mail, "password": password],encoding: JSONEncoding.default, headers: h ).responseJSON { (response) in
            completion(response)
        }
        
    }

}

/*
 email": "string",
 "password": "string"
 */
